# Utiliser l'image Python officielle
FROM python:3.11-slim

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances système nécessaires
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir flask flask-cors python-dotenv requests


RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir \
      flask flask-cors pillow numpy \
      "opencv-python-headless==4.10.0.84"

# Copier le code source
COPY . .

# Exposer le port sur lequel l'application Flask écoute
EXPOSE 5007

# Commande pour démarrer l'application d'analyse d'images
CMD ["python", "image_analyzer.py"]
